# Font
font_family      DroidSansM Nerd Font
font_size        12.0
bold_italic_font auto

# Window
confirm_os_window_close 0
window_padding_width 5
hide_window_decorations false
adjust_line_height 2
adjust_baseline 1
allow_remote_control true

# Cursor
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# Bell
enable_audio_bell false

# Tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Theme
include catppuccin-mocha.conf
