add_newline = true
command_timeout = 200

format = """\
[](#cba6f7)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$shell\
$nodejs\
$python\
$rust\
$golang\
$package\
$line_break\
$character"""

[character]
error_symbol = "[✗](bold #f38ba8)"
success_symbol = "[❯](bold #cba6f7)"

[cmd_duration]
format = "[$duration]($style) "
min_time = 2000
style = "#a6adc8"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold #cba6f7"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "#cdd6f4"

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "italic #cba6f7"
symbol = " "

[git_status]
format = '[$all_status]($style)'
style = "#cba6f7"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""

[golang]
format = "[$symbol($version )]($style)"
style = "bold #89dceb"
symbol = " "

[hostname]
disabled = false
format = "[$ssh_symbol](bold #cba6f7)[$hostname]($style) "
ssh_symbol = " "
style = "#a6adc8"

[nodejs]
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
format = "[$symbol($version )]($style)"
style = "bold #a6e3a1"
symbol = " "

[os]
disabled = false
style = "#cba6f7"

[package]
format = "[$symbol$version]($style) "
style = "bold #f9e2af"

[python]
format = "[$symbol($version )]($style)"
pyenv_version_name = true
style = "bold #89b4fa"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
style = "bold #fab387"
symbol = " "

[shell]
bash_indicator = " "
disabled = false
format = "[$indicator]($style) "
style = "#6c7086"

[username]
format = "[$user]($style) "
show_always = false
style_user = "#cba6f7"
style_root = "bold #f38ba8"
