# Execute your favorite apps at launch

# Chabed to be systemd service
exec-once = systemctl --user import-environment GTK_THEME MOZ_ENABLE_WAYLAND HYPRCURSOR_THEME HYPRCURSOR_SIZE
exec-once = systemctl --user start waybar.service
exec-once = nm-applet
exec-once = systemctl --user start dunst.service
exec-once = hyprpaper

## Need to figure out how to fix this
#exec-once = hyprctl keyword monitor "eDP-1, preferred, auto, 1.333333"
