# Mozilla
env = MOZ_ENABLE_WAYLAND,1

env = HYPRCURSOR_THEME,catppuccin-mocha-sky-cursors

env = GTK_THEME,catppuccin-mocha-mauve-standard+default

# Cursor size.
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland.
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

# Allow better support for screen sharing (Google Meet, Discord, etc).
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# GTK Scaling
env = GDK_SCALE,1
env = GDK_DPI_SCALE,1

# Qt Scaling (e.g., OBS, Kdenlive)
env = QT_SCALE_FACTOR,1.5
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Java/Electron Scaling (e.g., VS Code Flatpaks)
env = CLUTTER_SCALE,1.5

xwayland {
  force_zero_scaling = true
}
