dwindle {
    pseudotile = yes
    preserve_split = yes
    default_split_ratio = 1
    smart_split = no
    smart_resizing = yes
}

cursor  {
  hide_on_key_press = true
  warp_on_change_workspace = true
}

gesture = 4, horizontal, workspace

binds {
  hide_special_on_workspace_change=true
}
